name: Deploy to Firebase Hosting (staging)

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRIENDLY_MATCH_FINDER_STAGING }}"
          channelId: live
          projectId: matchbuddy-staging